### ISSUE TITLE
Build fails with lots of errors under VsStudio Express 2013 

### ISSUE THREAD

**Issue by daz10000** [fsprojects/FsLexYacc#1]
Tried a clean build from the current github source on a newish installation of VS2013 express.  I'm sure I'm missing some dependencies but it failed with a lot of errors below that didn't seem trivial.   I also tried the command line build script which did pull a bunch of dependencies but failed with similar messages.  I'm trying to migrate from the old Powerpack to this so I'd love to get it build.   I've used FsLexYacc heavily in a genetic engineering language we use at Amyris so great to see this getting its own project

Darren

------ Build started: Project: FsLex, Configuration: Debug Any CPU ------
C:\extproj\FsLexYacc\lkg\FSharp.PowerPack-1.9.7.7\bin\FSharp.PowerPack.targets(32,3): error MSB4036: The "FsLex" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\12.0\bin" directory.
Done building project "FsLex.fsproj" -- FAILED.

Build FAILED.
------ Build started: Project: FsYacc, Configuration: Debug Any CPU ------
C:\extproj\FsLexYacc\lkg\FSharp.PowerPack-1.9.7.7\bin\FSharp.PowerPack.targets(32,3): error MSB4036: The "FsLex" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\12.0\bin" directory.
Done building project "FsYacc.fsproj" -- FAILED.

Build FAILED.
------ Build started: Project: FsLexYacc.Runtime, Configuration: Debug Any CPU ------
	C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Debug\FsLexYacc.Runtime.dll -g --debug:full --noframework --doc:..\..\bin\Debug\FsLexYacc.Runtime.xml --optimize- --tailcalls- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" --target:library --warn:3 --warnaserror:76 --vserrors --validate-type-providers --LCID:1033 --utf8output --fullpaths --flaterrors --highentropyva- --sqmsessionguid:fd20fb9f-26ce-4128-8b36-1dc1cdf9becd "C:\Users\daz\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" AssemblyInfo.fs ..\FsLexYacc.Runtime\Lexing.fsi ..\FsLexYacc.Runtime\Lexing.fs ..\FsLexYacc.Runtime\Parsing.fsi ..\FsLexYacc.Runtime\Parsing.fs 
	FsLexYacc.Runtime -> C:\extproj\FsLexYacc\bin\Debug\FsLexYacc.Runtime.dll
------ Build started: Project: FsLexYacc.Build.Tasks, Configuration: Debug Any CPU ------
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Build.Utilities". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
	C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Debug\FsLexYacc.Build.Tasks.dll -g --debug:full --noframework --doc:..\..\bin\Debug\FsLexYacc.Build.Tasks.xml --optimize- --tailcalls- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.Build.Engine.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.Build.Framework.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" --target:library --warnaserror:76 --vserrors --validate-type-providers --LCID:1033 --utf8output --fullpaths --flaterrors --highentropyva- --sqmsessionguid:fd20fb9f-26ce-4128-8b36-1dc1cdf9becd "C:\Users\daz\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" AssemblyInfo.fs FsLex.Build.fs FsYacc.Build.fs 
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(7,22): error FS0039: The namespace 'Utilities' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(21,13): error FS0039: The type 'ToolTask' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(21,13): error FS0039: The type 'ToolTask' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(68,19): error FS0859: No abstract property was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(70,19): error FS0855: No abstract or interface member was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(73,19): error FS0855: No abstract or interface member was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLex.Build.fs(21,13): error FS0039: The type 'ToolTask' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(7,22): error FS0039: The namespace 'Utilities' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(14,13): error FS0039: The type 'ToolTask' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(14,13): error FS0039: The type 'ToolTask' is not defined
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(74,19): error FS0859: No abstract property was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(76,19): error FS0855: No abstract or interface member was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(79,19): error FS0855: No abstract or interface member was found that corresponds to this override
C:\extproj\FsLexYacc\src\FsLexYacc.Build.Tasks\FsYacc.Build.fs(14,13): error FS0039: The type 'ToolTask' is not defined
Done building project "FsLexYacc.Build.Tasks.fsproj" -- FAILED.

Build FAILED.
------ Build started: Project: FsLexYacc.Tests, Configuration: Debug Any CPU ------
	"C:\extproj\FsLexYacc\.nuget\NuGet.exe" install "C:\extproj\FsLexYacc\tests\FsLexYacc.Tests\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\extproj\FsLexYacc\ "
	Restoring NuGet packages...
	To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
	All packages listed in packages.config are already installed.
	Done building project "FsLex.fsproj" -- FAILED.
	Done building project "FsYacc.fsproj" -- FAILED.
	Done building project "FsLexYacc.Build.Tasks.fsproj" -- FAILED.
	Done building project "FsLex.fsproj" -- FAILED.
	Done building project "FsYacc.fsproj" -- FAILED.
	Done building project "FsLexYacc.Build.Tasks.fsproj" -- FAILED.
	C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Debug\FsLexYacc.Tests.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --doc:bin\Debug\FsLexYacc.Tests.XML --optimize- --tailcalls- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" -r:C:\extproj\FsLexYacc\bin\Debug\fslex.exe -r:C:\extproj\FsLexYacc\bin\Debug\FsLexYacc.Build.Tasks.dll -r:C:\extproj\FsLexYacc\bin\Debug\FsLexYacc.Runtime.dll -r:C:\extproj\FsLexYacc\bin\Debug\fsyacc.exe -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:C:\extproj\FsLexYacc\packages\NUnit.2.6.3\lib\nunit.framework.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Numerics.dll" --target:library --warn:3 --warnaserror:76 --vserrors --validate-type-providers --LCID:1033 --utf8output --fullpaths --flaterrors --highentropyva- --sqmsessionguid:fd20fb9f-26ce-4128-8b36-1dc1cdf9becd "C:\Users\daz\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" Tests.fs 
FSC: error FS0084: Assembly reference 'C:\extproj\FsLexYacc\bin\Debug\fslex.exe' was not found or is invalid
FSC: error FS0084: Assembly reference 'C:\extproj\FsLexYacc\bin\Debug\FsLexYacc.Build.Tasks.dll' was not found or is invalid
FSC: error FS0084: Assembly reference 'C:\extproj\FsLexYacc\bin\Debug\fsyacc.exe' was not found or is invalid
Done building project "FsLexYacc.Tests.fsproj" -- FAILED.

Build FAILED.
========== Build: 1 succeeded or up-to-date, 4 failed, 0 skipped ==========

**Comment by kkm000** [comment]
There is not a new Microsoft.Build.Utilities past 2.0.0.0, but for CLR 4 there is Microsoft.Build.Utilities.v4.0. This is what the new build tasks assembly is using.
