### ISSUE TITLE
Links in documentation website are broken

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/FsLexYacc#108]
### Description

The links in the Getting Started and Documentation section are broken.  They point to:

file:///C:/GitHub/dsyme/FsLexYacc/docs/fslex.html
file:///C:/GitHub/dsyme/FsLexYacc/docs/fsyacc.html
file:///C:/GitHub/dsyme/FsLexYacc/docs/reference/index.html

### Repro steps

Visit http://fsprojects.github.io/FsLexYacc/, look at the links at the bottom of the sidebar.

### Expected behavior

Links should point to the right place.

### Actual behavior

They don't.

### Known workarounds

Use the links in the main part of the page.

**Comment by sergey-tihon** [comment]
Fixed in #100 and site updated
