### ISSUE TITLE
Using F# keywords for non terminal names does not compile

### ISSUE THREAD

**Issue by thautwarm** [fsprojects/FsLexYacc#132]
### Description

Using F# keywords for non terminal names does not compile.

### Repro steps

FsYacc:

```bnf
%token HEAD

%type < unit list > start

%%

start : type { $1 }

type : { [] } 
	| HEAD type { ()::$2 }
```

### Expected behavior

Compile and produce the parser.

### Actual behavior

<details>
<summary> Log errors like this </summary>

```
$PROJ\lib\Parser.fs(195,107): error FS0010: Incomplete structured construct at or before this point in binding. Expected identifier or other token. [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,60): error FS0583: Unmatched '(' [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,22): error FS0583: Unmatched '(' [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,107): error FS0010: Unexpected keyword 'type' in binding. Expected incomplete structured construct at or before this point or other token. [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,13): error FS3118: Incomplete value or function definition. If this is in an expression, the body of the expression
must be indented to the same column as the 'let' keyword. [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,13): error FS0588: The block following this 'let' is unfinished. Every code block is an expression and must have a result. 'let' cannot be the final code element in a block. Consider giving this block an explicit result. [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(195,112): error FS0010: Unexpected symbol ')' in binding. Expected '|]' or other token. [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fs(183,33): error FS0603: Unmatched '[|' [$PROJ\lib\lib.fsproj]
$PROJ\lib\Parser.fsy(33,32): error FS0010: Unexpected symbol ')' in definition. Expected incomplete structured construct at or before this point or other token. [$PROJ\lib\lib.fsproj]
```

</details>

with such code generated:

```F#
let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'type)) in
```

### Known workarounds

Renaming the non terminal names to avoid keywords, e.g., `type` -> `typ`.

### Related information 

* OS: Win 10 10.0.19041 N/A Build 19041
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: CoreCLR 3.1.403

**Comment by gdziadkiewicz** [comment]
I wonder if compile error for `'<keyword>` or `^<keyword>` type parameters is expected in F# or if it's a bug in the compiler. I will try to check the specs.

If it's expected then your change solves the problem and if not then we can use it as a workaround for the compiler bug.

**Comment by gdziadkiewicz** [comment]
According to the syntax specs in https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf it works as expected.

**Comment by thautwarm** [comment]
According to the [specification](https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf)(search *type variable* in the pdf):

```bnf
type :=
 ( type )
 type -> type -- function type
 type * ... * type -- tuple type
 typar
 ...


typar :=
 _ -- anonymous variable type
 'ident -- type variable
 ^ident -- static head-type type variable
```

`ident-keyword` and `ident` seem to be distingushable according the specification, so I'd think `'type` is not a bug. 

However,  `'ident` can still be unexpected to the compiler team because I don't see a reason to reject type variables like `'type`.

**Comment by thautwarm** [comment]
appreciate for your fast check.
