### ISSUE TITLE
Building a project which uses FsLex/FsYacc fails when building with Visual Studio 2019

### ISSUE THREAD

**Issue by glenbraun** [fsprojects/FsLexYacc#142]
### Description

I've successfully used FsLexYacc for a few years but the latest version seems to assume the use of the command line of 'dotnet build xyz.sln', rather than using the Build menu inside VS2019. 

If it is not intended that this tool should work with VS2019 Build, then there isn't an issue.

### Repro steps

1. Create a new 'Console App (.NET Core)' project using Visual Studio 2019 (mine is public version)
2. Use 'Manage NuGet Packages...' option in VS2019, to add FsLexYacc (I'm using 10.2.0)
3. Like instructed here: https://fsprojects.github.io/FsLexYacc/fslex.html, create a lexer file (.fsl), add it to the project, set the Build Action to FsLex, modify the project to add the OtherFlags tag. 
4. Build using VS2019

Example:
```
<FsLex Include="IGLexer.fsl">
    <OtherFlags>--module IGLexer --unicode</OtherFlags>
</FsLex>
```

Similar issue for FsYacc.

### Expected behavior
Successful build - for the fslex and fsyacc tools to execute, to produce the lexer and parser .fs files and then continue with the remainder of the project build.

### Actual behavior
The build will fail with this output error:

    '"\"' is not recognized as an internal or external command,
    operable program or batch file.

### Known workarounds
I can build successfully from the command line using `dotnet build xyz.sln`. 

If only .NET Core, using command line builds is supported by the tool, it would be helpful to have a note about this in the documentation.

### Related information 

I find the issue to be that the value of '$(MSBuildRuntimeType)' is 'Core' when building from the 'dotnet build' command line. However, the value is 'Full' when building inside VS2019. You can add:
```
<Message Text="$(MSBuildRuntimeType)" Importance="high"/>
```

to the `<Target Name="CallFsLex">`, at around line 32 in FsLexYacc.targets file and view the output during the build. It should output 'Full'.

See conditions on 'MsBuildRuntimeType' in:
    
    <PropertyGroup>
        <CompileDependsOn>CallFsLex;CallFsYacc;$(CompileDependsOn)</CompileDependsOn>
        <FsLexToolPath Condition="'$(FsLexToolPath)' == '' AND '$(MSBuildRuntimeType)'=='Core'">$(MSBuildThisFileDirectory)/fslex/netcoreapp3.1</FsLexToolPath>
        <FsLexToolExe Condition="'$(FsLexToolExe)' == '' AND '$(MSBuildRuntimeType)'=='Core'">fslex.dll</FsLexToolExe>
        <FsYaccToolPath Condition="'$(FsYaccToolPath)' == '' AND '$(MSBuildRuntimeType)'=='Core'">$(MSBuildThisFileDirectory)/fsyacc/netcoreapp3.1</FsYaccToolPath>
        <FsYaccToolExe Condition="'$(FsYaccToolExe)' == '' AND '$(MSBuildRuntimeType)'=='Core'">fsyacc.dll</FsYaccToolExe>
        <FsLexYaccToolRunner Condition="'$(UseFsLexYaccToolRunner)' != 'false' AND '$(FsLexYaccToolRunner)' == '' AND '$(MSBuildRuntimeType)'=='Core'">dotnet </FsLexYaccToolRunner>
    </PropertyGroup>

* Operating system: Windows 10 Home
* Branch: Master
* Database versions and sample databases being used
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by manofstick** [comment]
Hi @glenbraun 

Building on your investigation, as I was having the same problem, I found that I could get it to work by setting all those msbuild variables within the fsproj file:

```xml
  <PropertyGroup>
    <FsLexToolPath>$(PkgFsLexYacc)\build\fslex\netcoreapp3.1</FsLexToolPath>
    <FsLexToolExe>fslex.dll</FsLexToolExe>
    <FsYaccToolPath>$(PkgFsLexYacc)\build\fsyacc\netcoreapp3.1</FsYaccToolPath>
    <FsYaccToolExe>fsyacc.dll</FsYaccToolExe>
    <FsLexYaccToolRunner>dotnet </FsLexYaccToolRunner>
  </PropertyGroup>
```

(Some docs I saw seemed to suggest that the package reference would need the `GeneratePathProperty` attribute set to get the `$(PkgFsLexYacc)` value set, but seemed to just work... Hmmm)

```xml
    <PackageReference Include="FsLexYacc" Version="10.2.0" GeneratePathProperty="true" />
```

**Comment by channell** [comment]
I fixed the issue by deleting "AND '$(MSBuildRuntimeType)'=='Core'" from the FsLexYacc.targets file

The issue seems to be an issue with the targets file not being updated for VS2019
