### ISSUE TITLE
.targets and build tools are packaged to /bin, not /build

### ISSUE THREAD

**Issue by kkm000** [fsprojects/FsLexYacc#26]
NuGet (starting with v2.5, I believe) will auto-import all .targets files from packaged /build directory to the project. I just built a package locally with the target file and all tools moved to /build, and it added its targets properly. With the binary package from nuget.org that does not happen.

Is this a bug or done on purpose?

**Comment by sergey-tihon** [comment]
As I understand there is no specific reason this.
[Facio](https://www.nuget.org/packages/Facio/) already uses `/build` folder, so I think that we can do the same for `FxLexYacc`
