### ISSUE TITLE
fslex emits: # 0 "" in output file -> breaks compilation

### ISSUE THREAD

**Issue by larsw** [fsprojects/FsLexYacc#3]
Hi,

 Running fslex on an input file, it outputs

// Implementation file for parser generated by fsyacc
module Parser
# nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type

open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
#0 ""

....

The # 0 "" results in an error from the F# compiler "Unexpected integer literal in directive. Expected identifier or other token."

If I enter some text between the quotes, it compiles.

**Comment by xionghuaidong** [comment]
I met this problem too. When the .fsy file has no %{ ... %} block, it will occur.
spec.Header (fsyacc.fs:152) should be initialized to work when the .fsy file has no %{ ... %} block.

**Comment by bitpushr** [comment]
I just got bit by this bug as well 😿 

Was scratching my head trying to figure out why I was getting a compile error, then I saw this issue.

Just adding `%{ %}` to my file mitigated the issue. This should really be fixed :/
