### ISSUE TITLE
Please rename Microsoft.Text.Lexing/Parsing to FsLexYacc.Runtime.Lexing/Parsing

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsLexYacc#35]
Now this project is on github as an independent "FsLexYacc" project, it's inappropriate for the Runtime component to be using the names 

```
Microsoft.Text.Lexing 
Microsoft.Text.Parsing
```

I suggest they be renamed to 

```
FsLexYacc.Runtime.Lexing
FsLexYacc.Runtime.Parsing
```

I think the rename should just be done and the minor version number bumped - it's a breaking change but a good one in the long term, and people who want the old naming can go to the old F# power pack. 

An alternative is 

```
FsLex.Runtime
FsYacc.Runtime
```

But I don't like that since the name of the overall technology is "FsLexYacc" and the two technologies really aren't independent in any particularly meaningful way.

**Comment by kkm000** [comment]
> the minor version number bumped

From [Semantic Versioning 2.0.0](http://semver.org/):

>Given a version number MAJOR.MINOR.PATCH, increment the:
>
>   MAJOR version when you make incompatible API changes,
>   MINOR version when you add functionality in a backwards-compatible manner, and
>   PATCH version when you make backwards-compatible bug fixes.

Looks like it is going to be 7.0.0.

**Comment by kkm000** [comment]
@jack-pappas: FYI. This is going to break Facio. Can you add [the upper exclusive bound](http://docs.nuget.org/create/versioning#specifying-version-ranges-in-.nuspec-files) of 7.0 in your next release?

No timeframe yet, but please subscribe to this ticket for updates.

**Comment by jack-pappas** [comment]
@kkm000 Sure, I can do that. I'll add the exclusive upper bound to the facio packages and publish them; once the new FsLexYacc packages are published for version 7.0, I'll update facio again so it requires a minimum version of 7.0 and generates code with the correct namespaces for the new versions.

**Comment by dsyme** [comment]
Cool, thanks for keeping an eye out. Looking forward to having this in.

**Comment by dsyme** [comment]
As far as I can see this has been completed a while back

**Comment by kkm000** [comment]
@dsyme: I do not believe it was, see [this, for example](https://github.com/fsprojects/FsLexYacc/blob/master/src/FsLexYacc/Runtime/Lexing.fs#L10), unless I am missing something. I'll put more priority on this, sorry for sitting on this for too long. I'll reopen the issue so it does not slip off my radar.

**Comment by dsyme** [comment]
Correct - sorry - I could have sworn we had addressed this!

**Comment by cartermp** [comment]
The 'Microsoft' is no longer present in source files, so closing this out.
