### ISSUE TITLE
Build fails on Mono as fs{lex,yacc}.exe not executable

### ISSUE THREAD

**Issue by rneatherway** [fsprojects/FsLexYacc#4]
Mono's Process.Start will not run a `.exe` file unless it is marked exectuable. It's not clear if this behaviour is deliberate or not. See this bug report: https://bugzilla.xamarin.com/show_bug.cgi?id=17537

The `lkg` bootstrap `fs{lex,yacc}.exe` do not have executable permission set and so the build fails (error at the bottom).

However, this is not just a problem for the build, if the permissions are not set in the NuGet package either, then this package cannot be used on Mono without a manual step (such as `find packages -name "*.exe" | xargs chmod +x`) after the package is downloaded. How can we address this? Is it possible to run a postinstall script on the package for example, or (less clean) to adjust the FsLex and FsYacc MSBuild tasks so that they set the executable bit on Mono before running?

```
/auto/users/robnea/dev/tmp/FsLexYacc/FsLexYacc.sln (Rebuild) ->
(Rebuild target) ->
/auto/users/robnea/dev/tmp/FsLexYacc/src/FsLex/FsLex.fsproj (Rebuild) ->
/auto/users/robnea/dev/tmp/FsLexYacc/lkg/FSharp.PowerPack-1.9.7.7/bin/FSharp.PowerPack.targets (CallFsLex target) ->

	/auto/users/robnea/dev/tmp/FsLexYacc/lkg/FSharp.PowerPack-1.9.7.7/bin/FSharp.PowerPack.targets: error : Error executing tool '../../lkg/FSharp.PowerPack-1.9.7.7/bin/FsLex.exe': ApplicationName='../../lkg/FSharp.PowerPack-1.9.7.7/bin/FsLex.exe', CommandLine='-o fslexlex.fs --unicode --lexlib Internal.Utilities.Text.Lexing  fslexlex.fsl ', CurrentDirectory='/auto/users/robnea/dev/tmp/FsLexYacc/src/FsLex', Native error= Cannot find the specified file

/auto/users/robnea/dev/tmp/FsLexYacc/FsLexYacc.sln (Rebuild) ->
(Rebuild target) ->
/auto/users/robnea/dev/tmp/FsLexYacc/src/FsYacc/FsYacc.fsproj (Rebuild) ->
/auto/users/robnea/dev/tmp/FsLexYacc/lkg/FSharp.PowerPack-1.9.7.7/bin/FSharp.PowerPack.targets (CallFsLex target) ->

	/auto/users/robnea/dev/tmp/FsLexYacc/lkg/FSharp.PowerPack-1.9.7.7/bin/FSharp.PowerPack.targets: error : Error executing tool '../../lkg/FSharp.PowerPack-1.9.7.7/bin/FsLex.exe': ApplicationName='../../lkg/FSharp.PowerPack-1.9.7.7/bin/FsLex.exe', CommandLine='-o fsyacclex.fs --unicode --lexlib Internal.Utilities.Text.Lexing  fsyacclex.fsl ', CurrentDirectory='/auto/users/robnea/dev/tmp/FsLexYacc/src/FsYacc', Native error= Cannot find the specified file
```

**Comment by rneatherway** [comment]
After this issue I submitted a PR to mono so that it still launches .exe files without +x. Happy to report it's now been merged (https://github.com/mono/mono/pull/1081) so I think we can close this.

**Comment by kkm000** [comment]
Thanks for checking!
