### ISSUE TITLE
Equals for NfaNodeIdSet always returns false

### ISSUE THREAD

**Issue by bronti** [fsprojects/FsLexYacc#41]
Overrided Equals for NfaNodeIdSet [here](https://github.com/fsprojects/FsLexYacc/blob/master/src/FsLex/fslexast.fs#L296) always returns false.

```
    let n = yr.Length

    xr.Length = n &&
    (let rec go i = (i < n) && xr.[i] = yr.[i] && go (i+1) 
    go 0)
```

Even if `xr` and  `yr` are equal, `(i < n)` eventually will become false making `go i` also false.

Possible fix:

```
    let n = yr.Length

    xr.Length = n &&
    (let rec go i = (i >= n) || xr.[i] = yr.[i] && go (i+1) 
    go 0)
```

Similar to https://github.com/YaccConstructor/YC.FST/issues/7

**Comment by kkm000** [comment]
Certainly a bug. Can you think of a test case that would currently break? Do we even use Equals?

**Comment by jimfoye** [comment]
The code looks likes it's been fixed

https://github.com/fsprojects/FsLexYacc/blob/06b47609f04b66ad553f7361c5a0e8aa6dc33924/src/FsLex.Core/fslexast.fs#L307

Should this issue be closed?

**Comment by dsyme** [comment]
Thanks!
