### ISSUE TITLE
add FSharp.Core as nuget package reference

### ISSUE THREAD

**Issue by enricosada** [fsprojects/FsLexYacc#46]
from @dsyme [comment](https://github.com/fsprojects/FsLexYacc/pull/45#issuecomment-182497734)

> Mono Linux doesn't come with Profile 7/78/259 assemblies for FSharp.Core as yet (I've asked Xamarin to add them). You might need to add a nuget package reference to FSharp.Core to get those. That would be a good thing to add anyway

**Comment by dsyme** [comment]
This is done

**Comment by dsyme** [comment]
Please see https://github.com/fsprojects/FsLexYacc/blob/master/nuget/FsLexYacc.Runtime.template#L18 to check, also dependency is listed here: https://www.nuget.org/packages/FsLexYacc.Runtime/
