### ISSUE TITLE
Cannot build LexAndYaccMiniProject on mono 3.2.7

### ISSUE THREAD

**Issue by rneatherway** [fsprojects/FsLexYacc#5]
This is independent of https://github.com/fsprojects/FsLexYacc/issues/4. After I set the executable bit to work around that issue, I then get a strange MSBuild issue. I had a look over the project file but I couldn't see anything obviously wrong. Perhaps my mono is too old?

```
Warnings:

:  warning : Default tasks file MSBuild/12.0/bin/Microsoft.Common.tasks not found, ignoring.

Errors:

LexAndYaccMiniProject.fsproj: error :
/auto/users/robnea/dev/tmp/FsLexYacc/tests/LexAndYaccMiniProject/LexAndYaccMiniProject.fsproj:
/home/scratch/local/lib/mono/xbuild/Microsoft/VisualStudio/v/FSharp/Microsoft.FSharp.Targets:
Project file could not be imported, it was being imported by
/auto/users/robnea/dev/tmp/FsLexYacc/tests/LexAndYaccMiniProject/LexAndYaccMiniProject.fsproj:
/home/scratch/local/lib/mono/4.0/Microsoft.FSharp.Targets:
Project file could not be imported, it was being imported by
/home/scratch/local/lib/mono/xbuild/Microsoft/VisualStudio/v/FSharp/Microsoft.FSharp.Targets:
/home/scratch/local/lib/mono/4.0/Microsoft.FSharp.Targets could
not import "$(MSBuildBinPath)\Microsoft.Common.targets"
```

**Comment by kkm000** [comment]
Is this still a problem for you? If not, please tell a bit about your resolution. 

When I am looking at it, this looks wrong:

     Microsoft/VisualStudio/v/FSharp/Microsoft.FSharp.Targets

Not the `/v/` bit: looks like it came from a substitution like `v${VisualStudioVersion}` without any sensible default set in your `.fsharp` project. I do not have mono, but it possible that the project would require a couple tweaks to compile under it.

Mot sure if this is FsLexYacc issue, but if you post the project file, I'll try to make sense of it.

**Comment by rneatherway** [comment]
I'm going to assume that this is a mono 3.2.X issue. On Linux with mono 3.4.0 I receive a different error:

```
  1) Building /home/robnea/dev/FsLexYacc/src/FsLexYacc.Profile7/FsLexYacc.Profile7.fsproj failed with exitcode 1.
  2) : /usr/local/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets(0,0): PCL Reference Assemblies not installed.
```

Perhaps the portable version is being built and should be disabled on Linux?

**Comment by kkm000** [comment]
I think the simplest solution would be to disable Profile7 like it is done to Profile259 [here](https://github.com/fsprojects/FsLexYacc/blob/master/build.fsx#L95). Could you please give it a quick try?

**Comment by rneatherway** [comment]
That works fine!

On Thu, Jan 22, 2015 at 8:33 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
It looks like your installation does not have PCL targets. Can they somehow be added? I am pretty naive about mono on linux, but [it is said that](http://lastexitcode.com/blog/2014/11/16/InstallingPortableClassLibrariesForXamarinStudio/)

> The Portable Class Libraries are included with the Mono Development Kit (MDK) but not with the Mono Runtime Environment (MRE). [...] The MDK includes the MRE as well as extra tools, libraries and the .NET Portable Class Library profiles.

I am not sure I have a clear picture of what are you trying to do. Why are you building the tools instead of pulling a pre-built nuget package? NuGet support on mono is limited by lack of PowerShell, but this package has no scripts. Or is it not a viable solution?

I am just not sure what the resolution for this might be. If mono/linux users must be able to build the tools without PCL targets available, then PCL profiles should not be build (and another profile is disabled anyway already).

**Comment by rneatherway** [comment]
Disabling the PCL target on Linux is fine. I am not using FsLexYacc at all
right now, but initially had the problem with the NuGet package caused by
the exec but issue we discussed and closed earlier. I believe your link is
talking about the Mac distribution, PCL reference assemblies are not
normally available on Linux for licencing reasons.

**Comment by kkm000** [comment]
I see. So I'll disable this target too.
