### ISSUE TITLE
Windows Appveyor build fails on alternate PRs

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FsLexYacc#53]
### Description

Since PR 50 the Appveyor Windows build has failed in OldFsYaccTests.fsx on every other build.

```
Running 'test1-unicode.exe' with args '--tokens .\test1.input1'
```

Although it fails at the same point, it seems to be arbitrary in that the next PR build will succeed, and I cannot replicate the failure locally.
### Repro steps

Merge PR. 
### Expected behavior

Appveyor should complete, and it does on alternate runs.
### Actual behavior

Fails after every other run
### Known workarounds

Build will eventually succeed on next run (if the pattern holds).
### Related information

Last failure on merge

```Create ISSUE_TEMPLATE.md

0.0.1.107

4 days ago  by Don Syme ```

**Comment by kkm000** [comment]
Looks like an EOL issue when comparing test output with the golden file. I think they have machines configured differently, and success/failure depends on which machine your test run hits.

**Comment by dsyme** [comment]
Suggest trying this in appveyor.yml (or some variation of this to some other CRLF setting)

```
init:
  - git config --global core.autocrlf input
```

**Comment by kkm000** [comment]
@dsyme: Let me look deeper into the issue. By the way, I seem to have no access to either Appveyor or Travis projects for FsLexYacc with GitHub OAuth identity. I can't e. g. restart a build. Maybe I am doing it wrong; but I also maintain another project on Travis, so I think this is just an access issue.

**Comment by kkm000** [comment]
I cannot prove but I think I found the culprit: https://github.com/fsharp/FAKE/pull/1211

**Comment by dsyme** [comment]
this is no longer happening
