### ISSUE TITLE
Suggestion for MSBuild docs

### ISSUE THREAD

**Issue by daz10000** [fsprojects/FsLexYacc#55]
### Description

I am finally getting around to automating fslex/yacc build after years of running it by hand on commandline.  The docs on home page are useful but missing some key details.  Suggest augmenting this page

http://fsprojects.github.io/FsLexYacc/fslex.html

Where page says:  You must also add FsLex and FsYacc entries like this:,   say WHERE those should go.  I'm experimentally inserting into MSBuild syntax but all insertions have caused errors in project file structure.  Apologies if this is obvious but I try to avoid touching msbuild and a quick sentence about where to insert would be super helpful

**Comment by daz10000** [comment]
The first line in the docs also appears to be wrong as of 6.1.0   I found those in the build not bin subfolder.

: 
<Import Project="..\packages\FsLexYacc.6.0.1\bin\FsLexYacc.targets" />

**Comment by dsyme** [comment]
I've made this adjustment to the docs, thanks

**Comment by cartermp** [comment]
Closing this out since the docs now refer to `PackageReference` as the preferred way to acquire and use the tool in a project.
