### ISSUE TITLE
Executable bit not set for tools in nuget package

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsLexYacc#64]
this is similar to https://github.com/fsharp/fsharp/issues/638

When you install the nuget package on mono/linux the executable bits for fslex.exe and fsyacc.exe should be automatically set

The worrkaround is to set it after installing the packages, e.g. https://github.com/dsyme/visualfsharp/blob/ae5b3ec722b64b9d44a28050d128876bfb259aa3/before_install.sh#L18

**Comment by cartermp** [comment]
This is no longer relevant with the move to .NET core only.
