### ISSUE TITLE
Issue with running fsyacc with -v flag

### ISSUE THREAD

**Issue by BartekSTRX** [fsprojects/FsLexYacc#66]
When run with -v flag, like this 
`fsyacc.exe -v --module ExprPar ExprPar.fsy`
fsyacc generates empty ExprPar.fsyacc.output file, and following error message

	building tables
	computing first function...        time: 00:00:00.0454196
	building kernels...        time: 00:00:00.0359272
	building kernel table...        time: 00:00:00.0101401
	computing lookahead relations...........................        time: 00:00:00.0167823
	building lookahead table...        time: 00:00:00.0080491
	building action table...        time: 00:00:00.0129263
	        building goto table...        time: 00:00:00.0005048
	        returning tables.
	writing tables to log
	.\packages\FsLexYacc.7.0.2\build\fsyacc.exe : FSYACC: error FSY000: Index was outside the bounds of the array.
	At line:1 char:1
	.\packages\FsLexYacc.7.0.2\build\fsyacc.exe -v --module ExprPar .\FsL ...
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	     CategoryInfo          : NotSpecified: (FSYACC: error F...s of the array.:String) [], RemoteException
	     FullyQualifiedErrorId : NativeCommandError

It should produce log file with description of parser as stack automaton. When run without -v flag, fsyacc correctly compiles *.fsy file and generates *.fs file with parser code. 

### Related information 
Problem observed on Windows 10, running fsyacc from Visual Studio 2015, nuget package version FsLexYacc 7.0.2.

**Comment by sergey-tihon** [comment]
I faced the same error using latest NuGet package,
@BartekSTRX please try version `6.1` - it works in my case

**Comment by sergey-tihon** [comment]
@BartekSTRX Please try latest `7.0.4` version, seems like it works in my case

**Comment by BartekSTRX** [comment]
Updated to version 7.0.5, seems to work, thanks.
