### ISSUE TITLE
How can I count/enumerate all syntax errors that occur while parsing?

### ISSUE THREAD

**Issue by siddharth-krishna** [fsprojects/FsLexYacc#72]
Sorry this is more a question than an issue. I know I can try-catch parse errors and get line number information from the lex buffer, but is it possible to count the number of syntax errors or get line numbers for all errors encountered? Or does this raise an exception on the first seen error?

**Comment by nshibano** [comment]
Hi,

First of all I am not expert in this area. This is just my opinions.

I think your understanding is correct. It throws exception. When parser encounters error, it can not recognize further tokens.

If you want to count number of errors, you can restart parsing from next token of the point first error was occur, or next semicolon, newline or something.

**Comment by siddharth-krishna** [comment]
I see, thank you for your help!

Siddharth

**Comment by cartermp** [comment]
@siddharth-krishna as others have mentioned here, a bespoke parser is the best approach if you want good error recovery. F# uses a generated parser but also has a layer that sits atop it that provides a lot of these kinds of things, in addition to a tooling host that can introspect things at different points when compared to a batch compilation process. It's not really a goal of this project to offer more intricate error recovery, so I'll close this one out.
