### ISSUE TITLE
FsLexYacc.Runtime.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by llly** [fsprojects/FsLexYacc#81]
I'm moving a F# project building dependencies from FsLexYacc 6.* to FsLexYacc 7.0.6.0. I can build it out successfully. But When running my executable I occur this failure:

``
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FsLexYacc.Runtime, Version=7.0.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
``

Then I checked FsLexYacc.Runtime.dll with sn:

```
>sn -vf FsLexYacc.Runtime.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

FsLexYacc.Runtime.dll does not represent a strongly named assembly
```

I looked though FsLexYacc.Runtime.fsproj and didn't find [signing process](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)

Of cause best solution is add signing process to project setting, officially or locally. 
Do I have workarounds to using prebuilt  FsLexYacc.Runtime.dll from NuGet? I don't want rebuild from source code.

**Comment by dsyme** [comment]
@llly Like many components (e.g. FSharp.Data) this DLL doesn't have a strong name.  There are endless arguments about whether such components  should be strong named, it's probably best to build and strong name it yourself for now

I agree guidance is probably that this component should have  a strong name

> I tried creating an unsigned package. People unhappy. I tried creating two packages. People unhappy. Eventually I just went with signing the assembly, freezing the assembly version at just major/minor versions, and nobody has complained since. I think the reality is this is the most accessible, least bad choice.

**Comment by llly** [comment]
Thanks. Now I build and sign FsLexYacc.Runtime locally.

**Comment by simonelnahas** [comment]
May i ask what commands you run( or refer to guide) to build and sign locally.
i'm experiencing the same issue

**Comment by sergey-tihon** [comment]
@simonelnahas just run build script https://github.com/fsprojects/FsLexYacc#releasing

But you do not need to rebuild `dll` from sources to get signed version. You can restore dependency from Nuget and sign `dll` before your build locally using [Mono.Cecil](https://www.nuget.org/packages/Mono.Cecil/)

For FAKE:
```fsharp
// --------------------------------------------------------------------------------------
// Sing unsigned assemblies

let keyBlob =
    @"MyKey.snk"
    |> Path.combine __SOURCE_DIRECTORY__
    |> IO.File.ReadAllBytes

let signAssembly (pathToDll:string) =
    let m = ModuleDefinition.ReadModule(pathToDll, ReaderParameters(InMemory=true))
    m.Write(pathToDll, WriterParameters(StrongNameKeyBlob=keyBlob))
    printfn "Successfully signed assembly '%s'" pathToDll

Target.create "SignAssemblies" (fun _ ->
    [
        @"packages/<todo>/FsLexYacc.Runtime.dll" // Relative path here
    ]
    |> List.iter signAssembly
)
```
