### ISSUE TITLE
Switch to SDK-style projects!

### ISSUE THREAD

**Issue by kkm000** [fsprojects/FsLexYacc#87]
@dsyme, I want to use SDK-style MSBuild projects instead of FAKE and Packet. These tools were a very good solution to packaging and dependency maintenance issues in "classic" projects, but these same problems are solved by dotnet SDK in a different way. I could not tame Paket to upgrade the runtime to make tests runnable on AppVeyor in #86--it kept inserting hundreds of lines of XML with target conditions into every project file. The SDK keeps this uglity under the hood.

This would take care of #78 as well.

What is your take on this? Can you think of a reason why we cannot use it?

**Comment by kkm000** [comment]
@sergey-tihon interesting, thanks. I noticed that FAKE 5 changes are quite major major, but did not go much deeper into it.

> How do you plan keep maintaining (compiling and publishing) site without the FAKE?

sed(1), just like this time? :)

Seriously, I thought about FSharp.Formatting.CommandTool. Do you happen to know any pros/cons of using it? Looks like a way to avoid loading both FSharp.Formatting runtime and FAKE runtime into the same domain. The [backtrace looks pretty ugly](https://github.com/fsprojects/FsLexYacc/pull/88#issue-223107323) (oddly, referencing the System.IO assembly explicitly did not help).

Also, site publishing is less tricky to get straight, as it's a manual, maintainer-only job. No concerns getting it running on AppVeyor, Travis and the kitchen sink, unlike the tests.

**Comment by daz10000** [comment]
I am not a pro here but the fake/paket experience for publishing with dotnet core is pretty straightforward (even fake 4) and I wouldn't want to go back.  Paket doesn't mess up the primary project file - it just inserts a single include line.  Yes the contents of that file are ugly,  but it's like machine code - you don't read it and something else generates it.

**Comment by kkm000** [comment]
@daz10000, and what are benefits of using packet with SDK projects?

**Comment by daz10000** [comment]
Same as with non SDK projects - principled package management,  efficient tracking and resolution of dependencies.  Lock files you can depend on to ensure reproducibility, clean audit trail of what went into a build,  lots of support for versioning and creating published packages, release docs etc.  (some of that from FAKE).   I don't have to think much about the release process and it really lowers the activation to do a revision.      I don't do anything larger than a small hello world type app nowadays without it and would never maintain anything that pushes out a final dll without it.    I don't think the SDK / non-SDK thing has any impact on paket utility.

**Comment by daz10000** [comment]
p.s. would love to get a clean dotnet build of fslexyacc runtime.  It is literally the last net461 dependency we have for a bunch of projects so let me know what I can do to help with this.

**Comment by kkm000** [comment]
@daz10000 Thank you for your offer, I'll keep that in mind!

**Comment by NatElkins** [comment]
@kkm000 I believe this issue can be closed.

**Comment by daz10000** [comment]
Agreed!  Thanks 

Von meinem iPhone gesendet

**Comment by kkm000** [comment]
Thanks @dsyme, sorry I could not get to do that : (
