### ISSUE TITLE
FSharp.Core Dependency

### ISSUE THREAD

**Issue by fangyi-zhou** [fsprojects/FsLexYacc#96]
FsLexYacc 9.0.2 added a new FSharp.Core dependency (>= 4.3.4 && < 4.4.0)
The constraint < 4.4.0 is causing some difficulty when using with other packages

**Comment by sergey-tihon** [comment]
it is very strange... 
@fangyi-zhou do you want to PR a fix?

It should be as simple as change one file
https://github.com/fsprojects/FsLexYacc/blob/master/nuget/FsLexYacc.template

and add one line at the bottom 
```
dependencies
  FsLexYacc.Runtime ~> CURRENTVERSION
```
like this
```
dependencies
  FsLexYacc.Runtime ~> CURRENTVERSION
  FSharp.Core >= LOCKEDVERSION
```

**Comment by mattiasw2** [comment]
But what do I do if I want to use a newer version of fsharp? I got this when I installed using nuget:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1608	Detected package version outside of dependency constraint: FsLexYacc 9.0.2 requires FSharp.Core (>= 4.3.4 && < 4.4.0) but version FSharp.Core 4.6.1 was resolved.	e2o2parser	C:\data3\ssc\ssc.master\ssc\e2o3\e2o2parser\e2o2parser.fsproj	1	
```

I also tried do clone the repo, and build myself and got

```
         dotnet "..\..\src\FsYacc\bin\Release\netcoreapp2.0\fsyacc.dll"  -o "Parser.fs" --module Parser Parser.fsy
     1>CallFsYacc:
                 building tables
         computing first function...        time: 00:00:00.0938070
         building kernels...        time: 00:00:00.0477577
         building kernel table...        time: 00:00:00.0173650
     1>FSYACC : error FSY000: The process cannot access the file 'c:\data-oss\fs\FsLexYacc\tests\JsonLexAndYaccExample\Parser.fs' because it is being used by another process. [c:\data-oss\fs\FsLexYacc\tests\JsonLexAndYaccExample\JsonLexAndYaccExample.fsproj]
     1>c:\data-oss\fs\FsLexYacc\src\FsLexYacc.Build.Tasks\FsLexYacc.targets(60,3): error MSB3073: The command "dotnet "..\..\src\FsYacc\bin\Release\netcoreapp2.0\fsyacc.dll"  -o "Parser.fs" --module Parser Parser.fsy" exited with code 1. [c:\data-oss\fs\FsLexYacc\tests\JsonLexAndYaccExample\JsonLexAndYaccExample.fsproj]
     1>Done Building Project "c:\data-oss\fs\FsLexYacc\tests\JsonLexAndYaccExample\JsonLexAndYaccExample.fsproj" (Build target(s)) -- FAILED.
     1>CallFsYacc:
         computing lookahead relations................................        time: 00:00:00.0354166
         building lookahead table...        time: 00:00:00.0098239
         building action table...        time: 00:00:00.0184304
                 building goto table...        time: 00:00:0
```

**Comment by mattiasw2** [comment]
I succeeded in building 8.0.1 locally

**Comment by daz10000** [comment]
Not sure if this is related but we are seeing some bizarre paket resolution issues with 9.0.1 requesting a version of FSharp.Core  >= 9.0.1.  Looks like the FSharp.Core version and FsLexYacc version are getting confused.   We've gone back to an 8 series FsLexYacc and pain went away so moving on but thought this might be relevant

![image](https://user-images.githubusercontent.com/6342645/57809316-14015f00-771a-11e9-99cd-834e7fe3553a.png)

**Comment by fangyi-zhou** [comment]
@daz10000 
https://www.nuget.org/packages/FsLexYacc/9.0.1 says it requires FSharp.Core (>= 9.0.1 && < 9.1.0).

**Comment by daz10000** [comment]
You are right, it's published that way.  So paket is at least not on drugs.  FSharp.Core versions are in the 4.6 range right now.  It looks as though the  FSLexYacc project's FSharp.Core dependency has been confused with the version of the project itself.  If this is a separate issue to the OP, I can create a new ticket

**Comment by sergey-tihon** [comment]
I've unlisted version `9.0.1` on NuGet, since we have `9.0.2` with correct dependencies

**Comment by daz10000** [comment]
9.0.2 is broken as well

![image](https://user-images.githubusercontent.com/6342645/57878427-d9a5c980-77ce-11e9-8b5f-deb81fe6c919.png)

**Comment by sergey-tihon** [comment]
Looks OK for me, what is broken?

**Comment by talyian** [comment]
Still getting the warnings in OP since most of my projects use FSharp.Core new than 4.3.x at this point.

Wouldn't this be addressed by changing the required version of FSharp.Core from `4.3.4`  to something more permissive, maybe `>= 4.3.4` in paket.dependencies?

**Comment by abbradar** [comment]
I still have this problem with 8.0.2, warning is:
```
Foo.fsproj : warning NU1608: Detected package version outside of dependency constraint: FsLexYacc 9.0.2 requires FSharp.Core (>= 4.3.4 && < 4.4.0) but version FSharp.Core 4.6.2 was resolved.
```

**Comment by EnCey** [comment]
So is there a hard dependency on FSharp.Core < 4.4.0 now or not?

**Comment by fangyi-zhou** [comment]
@EnCey Yes
https://www.nuget.org/packages/FsLexYacc/9.0.2
