### ISSUE TITLE
target file Error

### ISSUE THREAD

**Issue by kam1986** [fsprojects/FsLexYacc#99]
I'm currently trying to set up a simple  parser project to include in other project later so i just need to alter the fsl and fsp files. but at the moment I'm stock. This is first time I use Fsyacc in Visual studio. But i got the warning: The namespace 'Lexing' is not defined. when I try to call it from the fsl file. I use the example files given.

I think it's because of the error
The command
 ""C:\Users\KAM\.nuget\packages\fslexyacc\9.0.2\build\ /fsyacc/net46\fsyacc.exe"  -o "Lexer.fs" --unicode Lexer.fsl" exited with code 9009.

Do anyone no how to fix this ?

**Comment by talyian** [comment]
It's hard to diagnose your exact issue without any of your Lexer.fs available, but the namespace has recently changed from Microsoft.FSharp.Text.Lexing to FSharp.Text.Lexing, so you may need to remove the Microsoft if following older documentation
